#!/bin/bash

# Mobile App Build/Installation Script for Inventory Management System

echo "--- Mobile App Installation Guide ---"
echo ""
echo "This application is a Progressive Web App (PWA), which means it can be "
echo "installed on your mobile device directly from your browser without "
echo "needing an app store."
echo ""
echo "--- Prerequisites ---"
echo "1. The application must be hosted on a public server with HTTPS."
echo "   (PWAs require HTTPS to be installable on mobile)"
echo ""
echo "--- How to install on Android (Chrome/Edge) ---"
echo "1. Open the URL of your hosted application in Chrome."
echo "2. Tap the three-dot menu icon in the top right corner."
echo "3. Select 'Add to Home screen' or 'Install app'."
echo "4. Follow the prompts to add the app to your home screen."
echo ""
echo "--- How to install on iOS (Safari) ---"
echo "1. Open the URL of your hosted application in Safari."
echo "2. Tap the 'Share' icon (square with an arrow pointing up)."
echo "3. Scroll down and tap 'Add to Home Screen'."
echo "4. Name the app and tap 'Add'."
echo ""
echo "--- Building for Production ---"
echo "To prepare the app for hosting, run:"
echo "docker-compose -f docker-compose.prod.yml up --build -d"
echo ""
echo "--- Advance: Native Wrapper (Android APK) ---"
echo "If you specifically need an .apk file, you can use 'bubblewrap':"
echo "1. npm install -g @bubblewrap/cli"
echo "2. bubblewrap init --manifest=https://your-domain.com/manifest.json"
echo "3. bubblewrap build"
echo ""
echo "Note: Bubblewrap requires Android SDK and Java installed."
